routes/web.php
<?php

declare(strict_types=1);

use Bittacora\PublicMenu\Http\Controllers\MenuController;
use Illuminate\Support\Facades\Route;

Route::prefix('bpanel')->middleware(['web', 'auth','admin-menu'])->name('menu.')->group(function () {
    Route::get('menu', [MenuController::class, 'index'])->name('index');
    Route::get('menu/create', [MenuController::class, 'create'])->name('create');
    Route::post('menu/store', [MenuController::class, 'store'])->name('store');
    Route::get('menu/{model}/edit/language/{locale?}', [MenuController::class, 'editMenu'])->name('edit');
    Route::put('menu/{model}/update/language/{locale?}', [MenuController::class, 'update'])->name('update');
    Route::delete('menu/{model}', [MenuController::class, 'destroy'])->name('destroy');
    Route::get('menu/create-menu-item', [MenuController::class, 'createMenuItem'])->name('create-menu-item');
    Route::post('menu/reorder', [MenuController::class, 'reorder'])->name('reorder');
});

resources/views/create-menu-item.blade.php
@extends('bpanel/layouts.bpanel-app')

@section('title', 'Crear elemento del menú')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0 d-flex justify-content-between">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('menu::menu.add') }}</span>
            </h4>
        </div>

        <form class="mt-lg-3" autocomplete="off" method="post" action="{{route('page.store')}}">
            @csrf

            @livewire('form.input-text', ['name' => 'text', 'labelText' => __('menu::menu.text'), 'required' => true])
            @livewire('form.select', [ 'name' => 'type', 'required' => true, 'labelText' => 'Tipo de enlace', 'labelWidth' => 3, 'fieldWidth' => 7, 'allValues' => [
                'route' => 'Ruta del gestor',
                'url' => 'URL'
            ]])

            @livewire('form.input-text', ['name' => 'url', 'labelText' => __('menu::menu.url')])
            @livewire('form.input-text', ['name' => 'route', 'labelText' => __('menu::menu.route-name')])

            @livewire('form.input-text', ['name' => 'icon', 'labelText' => __('menu::menu.icon'), 'required' => true])

            @livewire('form.input-checkbox', ['name' => 'new_tab', 'value' => 0, 'labelText' => __('menu::menu.open-in-new-tab'), 'bpanelForm' => true])
            @livewire('form.input-checkbox', ['name' => 'active', 'value' => 1, 'labelText' => __('menu::menu.active'), 'bpanelForm' => true, 'checked' => 'checked'])

            <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
                @livewire('form.save-button',['theme'=>'save'])
                @livewire('form.save-button',['theme'=>'reset'])
            </div>
        </form>
    </div>
@endsection

@push('scripts')
    <script>

        /**
         * Muestra u oculta los campos para el nombre de la ruta o la URL según el tipo de enlace
         * @param value
         */
        function changeFieldsVisibility(value) {
            let routeField = $('#route');
            let urlField = $('#url');

            if (value === 'route') {
                routeField.closest('.form-group').show(0);
                routeField.attr('required', 'required');
                urlField.closest('.form-group').hide(0);
                urlField.removeAttr('required');
            } else {
                routeField.closest('.form-group').hide(0);
                routeField.removeAttr('required');
                urlField.closest('.form-group').show(0);
                urlField.attr('required', 'required');
            }
        }

        $(document).ready(function () {
            let $type = $('#type');
            changeFieldsVisibility($type.val());
            $type.change(function () {
                changeFieldsVisibility($(this).val());
            });

            let routeLabel = $('#route').closest('.form-group').find('label').prepend('<span class="text-danger">*</span>');
            let urlLabel = $('#url').closest('.form-group').find('label').prepend('<span class="text-danger">*</span>');
        });
    </script>
@endpush

resources/views/create-menu.blade.php
@extends('bpanel/layouts.bpanel-app')

@section('title', 'Crear nuevo menú')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0 d-flex justify-content-between">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('menu::menu.add') }}</span>
            </h4>
        </div>

        <form class="mt-lg-3" autocomplete="off" method="post" action="{{route('menu.store')}}">
            @csrf

            @livewire('form.input-text', ['name' => 'name', 'labelText' => __('menu::menu.name'), 'required' => true])
            @livewire('form.input-checkbox', ['name' => 'active', 'value' => 1, 'labelText' => __('menu::menu.active'), 'bpanelForm' => true, 'checked' => 'checked'])

            <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
                @livewire('form.save-button',['theme'=>'save'])
                @livewire('form.save-button',['theme'=>'reset'])
            </div>
            @livewire('form.input-hidden', ['name' => 'locale', 'value'=> $language])
        </form>
    </div>
@endsection

resources/views/edit-menu.blade.php
@extends('bpanel/layouts.bpanel-app')

@section('title', 'Editar menú')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0 d-flex justify-content-between">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('menu::menu.edit') }}</span>
            </h4>
        </div>

        <form class="mt-lg-3" autocomplete="off" method="post" action="{{route('menu.update', ['model' => $menu, 'locale' => $language])}}">
            @csrf

            @livewire('form.input-text', ['name' => 'name', 'labelText' => __('menu::menu.name'), 'required' => true, 'value' => $menu->name])
            @livewire('form.input-checkbox', ['name' => 'active', 'value' => 1, 'labelText' => __('menu::menu.active'), 'bpanelForm' => true, 'checked' => $menu->active == 1])

            <div class="mx-5">
                {!! Menu::render($menu->id.'_'.$language,$menu, $language) !!}
            </div>

            @push('scripts')
                {!! Menu::scripts() !!}
            @endpush

            <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
                @livewire('form.save-button',['theme'=>'save'])
                @livewire('form.save-button',['theme'=>'reset'])
            </div>
            @livewire('form.input-hidden', ['name' => 'locale', 'value'=> $language])
            @livewire('form.input-hidden', ['name' => 'id', 'value'=> $menu->id])
            <input type="hidden" name="_method" value="PUT">
        </form>


    </div>
@endsection

resources/views/index.blade.php
@extends('bpanel/layouts.bpanel-app')

@section('title', 'Menús')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('page::page.page_list') }}</span>
            </h4>
        </div>
        <div class="card-body">
            @livewire('public-menu-datatable')
        </div>
    </div>

@endsection

resources/views/livewire/datatable-checkbox.blade.php
<div class="form-check form-check-inline">
    <input class="form-check-input ace-switch input-sm"
           type="checkbox"
           @if($multiple) name="{{$name}}[]" @else name="{{$name}}" @endif
           id="{{$idField}}"
           wire:click="toggle({{$idField}})"
           @if($checked==1) checked @endif
    >
    @if(!is_null($labelText))
        <label class="form-check-label" for="{{$idField}}">{{ $labelText }}</label>
    @endif
</div>

resources/views/livewire/menu-datatable.blade.php
<td>
    {{ $row->name }}
</td>
<td class="text-center">
    @livewire('utils::datatable-default', ['fieldName' => 'active', 'model' => $row, 'value' => $row->active, 'size' => 'xxs'], key('active-blog-'.$row->id))
</td>
<td class="text-center">
    @livewire('language::datatable-languages', ['model' => $row, 'createRouteName' => 'menu.create', 'editRouteName' => 'menu.edit'], key('languages-menu-'.$row->id))
</td>
<td class="text-center">
    @livewire('utils::datatable-action-buttons', ['actions' => ["edit", "delete"], 'scope' => 'menu', 'model' => $row, 'permission' => ['edit', 'delete'], 'id' => $row->id, 'message' => 'el menú?'], key('blog-buttons-'.$row->id))
</td>

resources/views/livewire/public-menu.blade.php
<div>
    <div class="nav-wrap">
        <div class="btn-menu">
            <span></span>
        </div><!-- //mobile menu button -->
        <nav id="menu-{{ $slug }}" class="public-menu public-menu-{{ $slug }}">
            @if($publicMenu)
                <ul class="menu">
                    @foreach($publicMenu as $menu)
                        <li class="">
                            @if($menu['show'])
                                @if (Route::has($menu['link']))
                                    <a href="{{ route($menu['link']) }}" title="">{{ $menu['label'] }}</a>
                                @else
                                    <a href="{{ $menu['link'] }}" title="">{{ $menu['label'] }}</a>
                                @endif
                            @endif
                            @if( $menu['child'] )
                                <ul class="sub-menu">
                                    @foreach( $menu['child'] as $child )
                                        @if($child['show'])
                                        <li class="">
                                            @if (Route::has($child['link']))
                                                <a href="{{ route($child['link']) }}" title="">{{ $child['label'] }}</a>
                                            @else
                                                <a href="{{ $child['link'] }}" title="">{{ $child['label'] }}</a>
                                            @endif
                                        </li>
                                        @endif
                                    @endforeach
                                </ul><!-- /.sub-menu -->
                            @endif
                        </li>
                    @endforeach
                    @endif

                </ul><!-- /.menu -->
        </nav><!-- /#mainnav -->
    </div><!-- /.nav-wrap -->
</div>

resources/views/overrides/accordions/add-link.blade.php
@php
    $id = rand(100000, 999999);
@endphp
<div class="card">
    <div class="card-header" id="heading-{{$id}}">
        <h5 class="mb-0">
            <button type="button" class="btn btn-link" data-toggle="collapse"
            data-target="#collapse{{$id}}" 
            aria-expanded="true" aria-controls="collapse{{$id}}">
                Añadir enlace <i class="fa fa-angle-down narrow-icon float-right"></i>
            </button>
        </h5>
    </div>

    <div id="collapse{{$id}}" class="collapse" 
    aria-labelledby="heading{{$id}}" 
    data-parent="#accordion">
        <div class="card-body">
            <form method="GET">
                <div class="form-group">
                    <label for="label"><strong>Texto del enlace</strong></label>
                    <input type="text" class="form-control" name="label" placeholder="Label Menu">
                </div>
                <div class="form-group">
                    <label for="url"><strong>URL</strong></label>
                    <input type="text" class="form-control" name="url" placeholder="#">
                </div>
                <div class="form-group">
                    <label for="icon"><strong>Icono</strong></label>
                    <input type="text" class="form-control" id="iconHelp" name="icon" placeholder="Icon">
                    <small id="iconHelp" class="form-text text-muted">
                        Ejemplo: &lt;span class=&quot;oi oi-align-center&quot;&gt;&lt;/span&gt;
                    </small>
                </div>
                @if(!empty($roles))
                <div class="form-group">
                    <label for="role"><strong>Rol</strong></label>
                    <select class="form-control" name="role">
                        <option value="0">{{ __('Select Role') }}</option>
                        @foreach($roles as $role)
                            <option value="{{ $role->$role_pk }}">
                                {{ __(ucfirst($role->$role_title_field)) }}
                            </option>
                        @endforeach
                    </select>
                </div>
                @endif
                <div class="form-group">
                    <button type="button" onclick="addItemMenu(this, 'default')" 
                    class="btn btn-primary float-right mt-2 mb-4">
                        <i class="fas fa-plus"></i> Añadir al menú
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/overrides/accordions/default.blade.php
@php
    $id = rand(100000, 999999);
@endphp
<div class="card">
    <div class="card-header" id="heading-{{$id}}">
        <h5 class="mb-0">
            <button class="btn btn-link" data-toggle="collapse" 
            data-target="#collapse{{$id}}" 
            aria-expanded="true" aria-controls="collapse{{$id}}">
                {{$name}}
                <i class="fa fa-angle-down narrow-icon float-right"></i>
            </button>
        </h5>
    </div>

    <div id="collapse{{$id}}" class="collapse @isset($show) show @endisset" 
    aria-labelledby="heading{{$id}}" 
    data-parent="#accordion">
        <div class="card-body box-links-for-menu">
            <form method="get" action="">
                <div class="form-group">
                    <ul class="list-item">
                        @foreach ($urls as $key => $item)
                        <li>
                            <label for="menu-link-{{$id}}-{{$key}}">
                                <input 
                                id="menu-link-{{$id}}-{{$key}}"
                                class="" type="checkbox" name="menu_id"
                                value="{{$item['url']}}" 
                                data-icon="{{$item['icon']}}"
                                data-url="{{$item['url']}}"
                                data-label="{{$item['label']}}"
                                >
                                {{$item['label']}}
                            </label>
                        </li>
                        @endforeach
                    </ul>
                    <!-- <select name="pages" class="form-control data-select" required> -->
                    {{-- <select name="pages[]" multiple class="form-control data-select" required>
                        @foreach ($urls as $item)
                            <option 
                                value="{{$item['url']}}" 
                                data-icon="{{$item['icon']}}"
                                data-url="{{$item['url']}}"
                                >{{$item['label']}}</option>
                        @endforeach
                    </select> --}}
                </div>
                @if(!empty($roles))
                <div class="form-group">
                    <label for="role">Example select</label>
                    <select class="form-control" name="role">
                        <option value="0">Select Role</option>
                        @foreach($roles as $role)
                            <option value="{{ $role->$role_pk }}">
                                {{ ucfirst($role->$role_title_field) }}
                            </option>
                        @endforeach
                    </select>
                </div>
                @endif
                <div class="form-group">
                    <button type="button" onclick="addItemMenu(this, 'custom')" 
                    class="btn btn-info btn-sm float-right mr-2 mb-2">
                        Add to Menu
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/overrides/menu-html.blade.php
@php
    $currentUrl = url()->current();
@endphp

<link href="{{ Vite::asset('vendor/bittacora/laravel-menu/public/style.css')}}" rel="stylesheet">

<style>
    .dd-handle {
        cursor: move;
        color: #333;
        text-decoration: none;
        background: transparent;
        padding: 13px;
        margin-left: -0.9rem;
    }

    .dd-handle:hover {
        color: #2a80c8;
        background: transparent;
    }
</style>

<div id="nguyen-huy" class="card mt-2 mb-2">
    <div class="card-header">
        <strong>Editar menú</strong>
    </div>

    <div class="card-body">
        <input type="hidden" id="idmenu" value="{{$indmenu->id ?? null}}"/>
        <input type="hidden" id="menu-slug" value="{{$indmenu->slug}}"/>
        <div class="row">
            <div class="col-md-4">
                @include('bpanel4-public-menu::overrides.partials.left')
            </div>
            {{-- /col-md-4 --}}
            <div class="col-md-8">
                @include('bpanel4-public-menu::overrides.partials.right')
            </div>
        </div>
    </div>

    <div class="ajax-loader" id="ajax_loader">
        <div class="lds-ripple">
            <div></div>
            <div></div>
        </div>
    </div>
</div>

resources/views/overrides/partials/left.blade.php
<div id="accordion-left">
    @include('bpanel4-public-menu::overrides.accordions.add-link', ['name' => 'Add Link'])
</div>

resources/views/overrides/partials/loop-item.blade.php
<li data-id="{{$m['id']}}" class="dd-item mb-2">
    <div class="card-header">
        <span class="dd-handle"><i class="fa fa-arrows" aria-hidden="true"></i></span>
        <span class="item-title">
            <span class="menu-item-title font-weight-bold"> 
                {{$m['label']}}
            </span>
            /
            <span class="menu-item-link font-weight-light"> 
                {{ \Illuminate\Support\Str::limit($m['link'], $limit = 30, $end = '...') }}
            </span>
            <span style="color: transparent;">|{{$m['id']}}|</span>
        </span>
        <div class="card-link float-right" data-toggle="collapse" href="#collapse{{$m['id']}}">
            <span class="item-controls"> 
                <span class="item-type">Enlace <i class="fa fa-angle-down narrow-icon" aria-hidden="true"></i></span>
            </span>
        </div>
    </div>
    {{-- @if($key == 0) show @endif --}}
    <div id="collapse{{$m['id']}}" class="collapse " data-parent="#accordion">
        <div class="card-body">
            <div class="menu-item-settings" id="menu-item-settings-{{$m['id']}}">
                <input type="hidden" class="edit-menu-item-id" name="menuid_{{$m['id']}}" value="{{$m['id']}}" />
                <div class="form-group">
                    <label for=""><strong>Texto</strong></label>
                    <input id="label-menu-{{$m['id']}}" class="form-control edit-menu-item-title" 
                    name="label-menu-{{$m['id']}}" value="{{$m['label']}}">
                </div>
                <div class="form-group">
                    <label for=""><strong>URL</strong></label>
                    <input id="url-menu-{{$m['id']}}" class="form-control edit-menu-item-url" 
                    name="url-menu-{{$m['id']}}" value="{{$m['link']}}">
                </div>
                <div class="form-group">
                    <label for=""><strong>Clase CSS (opcional)</strong></label>
                    <input id="clases-menu-{{$m['id']}}" class="form-control edit-menu-item-classes" 
                    name="clases-menu-{{$m['id']}}" value="{{$m['class']}}">
                </div>
                <div class="form-group">
                    <label for=""><strong>Icono</strong></label>
                    <input id="icon-menu-{{$m['id']}}" class="form-control edit-menu-item-icon" 
                    name="icon-menu-{{$m['id']}}" value="{{$m['icon']}}">
                </div>
                @if(!empty($roles))
                <div class="form-group">
                    <label for="edit-menu-item-role-{{$m['id']}}"><strong>Rol</strong></label>
                    <select id="role_menu_{{$m['id']}}" class="form-control edit-menu-item-role" 
                        name="role_menu_[{{$m['id']}}]" >
                        <option value="0">{{ __('Select Role') }}</option>
                        @foreach($roles as $role)
                            <option @if($role->id == $m['role_id']) selected @endif value="{{ $role->$role_pk }}">
                                {{ __(ucwords($role->$role_title_field)) }}
                            </option>
                        @endforeach
                    </select>
                </div>
                @endif
                <div class="form-group">
                    @php
                        $target = [
                            '_self' => 'Abrir en la misma pestaña',
                            '_blank' => 'Abrir en una pestaña nueva',
                        ]
                    @endphp
                    <label for=""><strong>Destino</strong></label>
                    <select name="target" class="form-control edit-menu-item-target" id="target-menu-{{$m['id']}}">
                        @foreach ($target as $key => $item)
                            <option value="{{$key}}" @if($key == $m['target']) selected @endif>{{$item}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <button type="button" onclick="deleteItem({{$m['id']}})" class="btn btn-danger"
                        id="delete-{{$m['id']}}" href="javascript:void(0)">Quitar</button>
                    <button type="button" onclick="updateItem({{$m['id']}})" class="btn btn-primary"
                        id="update-{{$m['id']}}" href="javascript:void(0)">Actualizar</button>
                </div>
            </div>
        </div>
    </div>
    @if (isset($m['child']) && count($m['child']) > 0)
    <ol class="dd-list">
        @foreach($m['child'] as $_m)
            @include('bpanel4-public-menu::overrides.partials.loop-item', ['m' => $_m, 'key' => 1])
        @endforeach
    </ol>
    @endif
</li>

resources/views/overrides/partials/right.blade.php
<div class="card mt-2">
    <input name="menu-name" id="menu-name" type="hidden" value="@if(isset($indmenu)){{$indmenu->name}}@endif">
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                @if(request()->get('menu') != 0 && isset($menus) && count($menus) > 0)
                    <div class="jumbotron jumbotron-fluid p-2">
                        <div class="container">
                            <h3>Estructura del menú</h3>
                            <p class="lead">
                                Coloque cada elemento en el orden deseado. Haga click en <i
                                        class="fa fa-pencil-square-o" aria-hidden="true"></i> a la derecha del elemento para mostrar más opciones.</p>
                        </div>
                    </div>
                @elseif(request()->get('menu') == 0)
                @else
                    <div class="jumbotron jumbotron-fluid p-2">
                        <div class="container">
                            <h3>Crear elemento del menú</h3>
                            <p class="lead"></p>
                        </div>
                    </div>
                @endif

                <div id="accordion" class="">
                    @if(isset($menus) && count($menus) > 0)
                        <div class="dd nestable-menu" id="nestable">
                            <ol class="dd-list">
                                @foreach($menus as $key => $m)
                                    @include('bpanel4-public-menu::overrides.partials.loop-item', ['key' => $key])
                                @endforeach
                            </ol>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
    @if(request()->get('menu') != 0)
        <div class="card-footer">
            <button type="button" class="btn btn-danger btn-sm submitdelete deletion menu-delete"
                    onclick="deleteMenu()" href="javascript:void(9)">Delete Menu
            </button>
            @if(isset($menus) && count($menus) > 0)
                <button type="button" class="btn btn-info btn-sm"
                        onclick="updateItem()" href="javascript:void(9)">Update All Item
                </button>
            @endif
        </div>
    @endif
</div>

resources/views/partials/actions.blade.php
<div class="action-buttons">
    <a class="text-success mx-2" href="{{route($scope.'.edit', $id)}}">
        <i class="fa fa-pencil"></i>
    </a>
    <form method="POST" class="d-inline mx-2"
          action="{{route($scope.'.destroy', $id)}}">
        {!!method_field('DELETE')!!}
        @csrf
        <button id="delete_button{{$id}}" type="submit" class="btn btn-primary-outline text-danger"
                @if($disabled) disabled @endif
                onclick="return confirm('¿Está seguro de querer borrar {{$message}}')">
            <i class="fa fa-trash"></i>
        </button>
    </form>
</div>

resources/views/partials/active.blade.php
<div class="text-center">
    @livewire('menu-datatable-checkbox',[
    'idField' => $idField,
    'name' => $name,
    'checked' => $checked,
 ])
</div>

resources/views/partials/default.blade.php
<div class="text-center">
    @livewire('page-datatable-default',[
    'idField' => $idField,
    'name' => $name,
    'value' => $value,
 ])
</div>